services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./volumes/sribia_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sribia
  web:
    image: ghcr.io/melinakrzemowa/sribia:${VERSION}
    restart: unless-stopped
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ecto://postgres:postgres@db/sribia
      HOST: ${HOST}
      VERSION: ${VERSION}
    ports:
      - "${PORT}:4000"
    depends_on:
      - db
