name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get the hash
      id: get_hash
      run: |
        echo ::set-output name=HASH::${GITHUB_SHA::8}

    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          kelu/sribia:latest
          kelu/sribia:${{ steps.previoustag.outputs.tag }}-${{ steps.get_hash.outputs.HASH }}

    - name: Copy docker-compose.yml
      uses: appleboy/scp-action@master
      with:
        host: sribia.melinakrzemowa.pl
        username: kelu
        key: ${{ secrets.PRIVATE_KEY }}
        source: "docker-compose.yml"
        target: "/var/www/sribia.melinakrzemowa.pl"
        overwrite: true

    - name: Update service using docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: sribia.melinakrzemowa.pl
        username: kelu
        key: ${{ secrets.PRIVATE_KEY }}
        script: export VERSION=${{ steps.previoustag.outputs.tag }}-${{ steps.get_hash.outputs.HASH }} && cd /var/www/sribia.melinakrzemowa.pl && docker-compose up --no-deps -d web
